routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-hash-en'
    order: published_at asc

  /en/:
    permalink: /en/{slug}/
    template: index-en
    filter: 'tag:hash-en'
    order: published_at asc

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/